import detailsData from "./product-details.data.json";
import type { Spec, Section, DocumentLink, Review } from "./products";

// Heavy product data — only loaded on the product detail page.
// Generated by scripts/gen-products.mjs into product-details.data.json,
// keyed by product slug. Kept out of the site-wide bundle (the cart
// context imports lib/products, so anything on the light Product type
// ships everywhere; heavy fields must stay here).
export type ProductDetails = {
  images: string[];
  labels: string[];
  description: string;
  specs: Spec[];
  documents: DocumentLink[];
  sections: Section[];
  reviews: Review[];
  reviewCount: number;
};

const map = detailsData as unknown as Record<string, ProductDetails>;

export function getProductDetails(slug: string): ProductDetails | undefined {
  return map[slug];
}
