import type { IconName } from "@/components/Icon";
import productsData from "./products.data.json";

// Product catalogue.
// - `categories` is hand-maintained taxonomy (8 categories + subcategories).
// - `products` is imported from products.data.json, generated by
//   scripts/gen-products.mjs out of the ecosoft.ua catalogue export.

export type Subcategory = {
  slug: string;
  title: string;
};

export type Category = {
  slug: string;
  title: string;
  description: string;
  icon: IconName;
  subcategories: Subcategory[];
};

export type Membership = {
  category: string;
  subcategory?: string;
};

export type Spec = {
  name: string;
  value: string;
};

export type DocumentLink = {
  title: string;
  url: string;
};

export type Section = {
  title: string;
  body: string;
};

export type Review = {
  author: string;
  date: string;
  text: string;
};

// Lightweight product used across the site (catalog, cards, cart, home).
// Heavy fields (gallery, full description, specs, documents, sections, reviews)
// live in lib/product-details.ts and are loaded only on the product page.
export type Product = {
  id: string;
  slug: string;
  name: string;
  sku: string;
  brand?: string;
  url?: string;
  category: string; // primary category slug
  subcategory?: string; // primary subcategory slug
  memberships: Membership[]; // all category/subcategory placements
  price: number; // UAH
  oldPrice?: number;
  image?: string | null; // primary image (for cards)
  shortDescription: string;
  features: string[];
  badge?: string;
  inStock: boolean;
};

export const categories: Category[] = [
  {
    slug: "reverse-osmosis",
    title: "Фільтри зворотного осмосу",
    description:
      "Багатоступеневе очищення води до рівня питної. Видаляють до 99,8% домішок, солей, бактерій і вірусів.",
    icon: "osmosis",
    subcategories: [
      { slug: "ro-pure", title: "PURE з мінералізацією" },
      { slug: "ro-absolute", title: "Absolute" },
      { slug: "ro-standard", title: "Standard" },
      { slug: "ro-cross", title: "Смарт CROSS" },
    ],
  },
  {
    slug: "flow-filters",
    title: "Проточні фільтри",
    description:
      "Системи під мийку для щоденного очищення питної води. Швидкий потік без накопичувального бака.",
    icon: "drop",
    subcategories: [{ slug: "flow-triple", title: "Потрійні системи" }],
  },
  {
    slug: "filtration-systems",
    title: "Фільтраційні системи",
    description:
      "Комплексне очищення води для дому — від заліза, жорсткості, хлору та сірководню до механічних домішок.",
    icon: "gear",
    subcategories: [
      { slug: "fs-compact", title: "Компактні системи" },
      { slug: "fs-iron-hardness", title: "Від заліза та твердості" },
      { slug: "fs-column", title: "Колонного типу" },
      { slug: "fs-softening", title: "Пом'якшення води" },
      { slug: "fs-chlorine", title: "Видалення хлору" },
      { slug: "fs-h2s", title: "Від сірководню" },
      { slug: "fs-mechanical", title: "Механічного очищення" },
    ],
  },
  {
    slug: "mainline-filters",
    title: "Магістральні фільтри",
    description:
      "Очищення води на вході у квартиру чи будинок. Захищають сантехніку й техніку від домішок, іржі та накипу.",
    icon: "filter",
    subcategories: [
      { slug: "ml-flushing", title: "Промивні" },
      { slug: "ml-cartridge", title: "Картриджні" },
      { slug: "ml-antiscale", title: "Від накипу" },
      { slug: "ml-hot", title: "Для гарячої води" },
      { slug: "ml-cold", title: "Для холодної води" },
    ],
  },
  {
    slug: "ro-cartridges",
    title: "Картриджі для фільтрів води",
    description:
      "Оригінальні змінні картриджі та мембрани Ecosoft для систем осмосу й проточних фільтрів.",
    icon: "cartridge",
    subcategories: [
      { slug: "roc-standard", title: "Standard" },
      { slug: "roc-absolute", title: "Absolute" },
      { slug: "roc-pure", title: "PURE" },
      { slug: "roc-flow", title: "Для проточних фільтрів" },
    ],
  },
  {
    slug: "mainline-cartridges",
    title: "Картриджі для магістральних фільтрів",
    description:
      "Змінні картриджі типорозмірів Standard і Big Blue для магістральних корпусів Ecosoft.",
    icon: "accessory",
    subcategories: [
      { slug: "mlc-standard", title: 'Standard 2,5"×10"' },
      { slug: "mlc-bb10", title: 'BB10 4,5"×10"' },
      { slug: "mlc-bb20", title: 'BB20 4,5"×20"' },
      { slug: "mlc-antiscale", title: "Від накипу" },
    ],
  },
  {
    slug: "filter-media",
    title: "Матеріали для фільтраційних систем",
    description:
      "Засипки та реагенти для завантаження й обслуговування фільтраційних колон і систем пом'якшення.",
    icon: "leaf",
    subcategories: [
      { slug: "fm-ecomix", title: "Ecomix" },
      { slug: "fm-salt", title: "Таблетована сіль" },
      { slug: "fm-carbon", title: "Вугілля" },
      { slug: "fm-resin", title: "Іонообмінні смоли" },
      { slug: "fm-mechanical", title: "Для механічної фільтрації" },
    ],
  },
  {
    slug: "horeca",
    title: "Фільтри для кафе, ресторанів, готелів",
    description:
      "Професійні рішення водопідготовки для HoReCa — для кавомашин, пароконвектоматів та льодогенераторів.",
    icon: "award",
    subcategories: [],
  },
];

export const products: Product[] = productsData as unknown as Product[];

export function getProduct(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getCategory(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getSubcategory(
  categorySlug: string,
  subSlug: string
): Subcategory | undefined {
  return getCategory(categorySlug)?.subcategories.find((s) => s.slug === subSlug);
}

export function productInCategory(
  product: Product,
  categorySlug?: string,
  subSlug?: string
): boolean {
  if (!categorySlug) return true;
  return product.memberships.some(
    (m) => m.category === categorySlug && (!subSlug || m.subcategory === subSlug)
  );
}

export function productsByCategory(slug: string): Product[] {
  return products.filter((p) => productInCategory(p, slug));
}

export function formatPrice(uah: number): string {
  return new Intl.NumberFormat("uk-UA").format(uah) + " ₴";
}
